# Generated by Django 4.2.30 on 2026-05-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='muscle_group',
            field=models.CharField(choices=[('Arms', 'Arms'), ('Chest', 'Chest'), ('Back', 'Back'), ('Legs', 'Legs'), ('Shoulders', 'Shoulders'), ('Core', 'Core')], default='Arms', max_length=20),
        ),
        migrations.AlterField(
            model_name='workout',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
