# Generated by Django 4.2.30 on 2026-06-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutroutine',
            name='colour',
            field=models.CharField(choices=[('blue', 'Blue'), ('green', 'Green'), ('red', 'Red'), ('orange', 'Orange'), ('purple', 'Purple'), ('pink', 'Pink'), ('yellow', 'Yellow'), ('cyan', 'Cyan'), ('magenta', 'Magenta'), ('teal', 'Teal'), ('indigo', 'Indigo'), ('lime', 'Lime')], default='blue', max_length=20),
        ),
    ]
